<?php
$ts = array("A+","A-","B+","B-","O+","O-","AB+","AB-",);


$listaDonantes = array();

$listaDonantes[] = array("Mauricio", "O+", "72014520");
$listaDonantes[] = array("Yery", "O+", "70254230");
$listaDonantes[] = array("Gerson", "B-", "74589621");
$listaDonantes[] = array("Edwar", "O-", "74589622");
$listaDonantes[] = array("Joel", "A+", "77854120");
$listaDonantes[] = array("Dilan", "O+", "77465823");
?>