<?php
// para el index
$ti = array("Casa", "Departamento", "Quinta", "Oficina", "Terreno");
$tc = array("Alquiler","Venta");

// para el resultado
$listaInmuebles = array();

$listaInmuebles[] = array("Casa", "Av. Beni", 100000, "78210148", "Venta");
$listaInmuebles[] = array("Casa", "Barrio Lujan", 40000, "77854120", "Venta");
$listaInmuebles[] = array("Departamento", "Av. Moscú", 75000, "70254230", "Venta");
$listaInmuebles[] = array("Departamento", "Zoologico", 155000, "77461687", "Venta");
$listaInmuebles[] = array("Quinta", "", 80000, "74589621", "Venta");
$listaInmuebles[] = array("Quinta", "Urubó", 150000, "77465823", "Venta");
$listaInmuebles[] = array("Oficina", "Casco Viejo", 10000, "74589622", "Venta");
$listaInmuebles[] = array("Oficina", "24 de Septiembre", 250000, "77852149", "Venta");
$listaInmuebles[] = array("Casa", "Barrio Lujan", 1500, "77854120", "Alquiler");
$listaInmuebles[] = array("Quinta", "Urubó", 3500, "77465823", "Alquiler");
$listaInmuebles[] = array("Departamento", "Zoologico", 2000, "77461687", "Alquiler");
$listaInmuebles[] = array("Oficina", "24 de Septiembre", 2500, "77852149", "Alquiler");


?>