<?php
// para tipo de pizza
$platofuere = array();
$platofuere[] = array("idfuerte" => 1, "nombre" => "Ojo de Bife", "precio" => "70");
$platofuere[] = array("idfuerte" => 2, "nombre" => "Picaña Premiun", "precio" => "80");
$platofuere[] = array("idfuerte" => 3, "nombre" => "Costillas de Cerdo con salsa Barbecue", "precio" => "60");
$platofuere[] = array("idfuerte" => 4, "nombre" => "Tomahawk", "precio" => "80");

// para tipo de pizza
$postre = array();
$postre[] = array("idpostre" => 1, "nombre" => "Tres leches con rom", "precio" => "20");
$postre[] = array("idpostre" => 2, "nombre" => "Mousse de Chocolate", "precio" => "25");
$postre[] = array("idpostre" => 3, "nombre" => "cheesecake de oreo", "precio" => "20");
$postre[] = array("idpostre" => 4, "nombre" => "Tarta de Queso", "precio" => "30");

// para tipo de tamaño
$bebida = array();
$bebida[] = array("idbebida" => 1, "nombre" => "Limonada de limon", "precio" => "20");
$bebida[] = array("idbebida" => 2, "nombre" => "Cerveza Paceña", "precio" => "25");
$bebida[] = array("idbebida" => 3, "nombre" => "Vino Pateño", "precio" => "70");
$bebida[] = array("idbebida" => 4, "nombre" => "Blue Label", "precio" => "1500");

// para el resultado
$listaPizzas = array();

$listaPizzas[] = array("idTamaño" => 1, "nombres" => "Grande", "precio" => 55, "idTipo" => 1, "nombre" => "4 Quesos");
$listaPizzas[] = array("idTamaño" => 2, "nombres" => "Mediana", "precio" => 35, "idTipo" => 1, "nombre" => "4 Quesos");
$listaPizzas[] = array("idTamaño" => 3, "nombres" => "Personal", "precio" => 25, "idTipo" => 1, "nombre" => "4 Quesos");
$listaPizzas[] = array("idTamaño" => 4, "nombres" => "Extra Grande", "precio" => 75, "idTipo" => 1, "nombre" => "4 Quesos");
$listaPizzas[] = array("idTamaño" => 1, "nombres" => "Grande", "precio" => 55, "idTipo" => 2, "nombre" => "Margarita");
$listaPizzas[] = array("idTamaño" => 2, "nombres" => "Mediana", "precio" => 35, "idTipo" => 2, "nombre" => "Margarita");
$listaPizzas[] = array("idTamaño" => 3, "nombres" => "Personal", "precio" => 25, "idTipo" => 2, "nombre" => "Margarita");
$listaPizzas[] = array("idTamaño" => 4, "nombres" => "Extra Grande", "precio" => 75, "idTipo" => 2, "nombre" => "Margarita");
$listaPizzas[] = array("idTamaño" => 1, "nombres" => "Grande", "precio" => 55, "idTipo" => 3, "nombre" => "Peperoni");
$listaPizzas[] = array("idTamaño" => 2, "nombres" => "Mediana", "precio" => 35, "idTipo" => 3, "nombre" => "Peperoni");
$listaPizzas[] = array("idTamaño" => 3, "nombres" => "Personal", "precio" => 25, "idTipo" => 3, "nombre" => "Peperoni");
$listaPizzas[] = array("idTamaño" => 4, "nombres" => "Extra Grande", "precio" => 75, "idTipo" => 3, "nombre" => "Peperoni");
$listaPizzas[] = array("idTamaño" => 1, "nombres" => "Grande", "precio" => 55, "idTipo" => 4, "nombre" => "Hawaiana");
$listaPizzas[] = array("idTamaño" => 2, "nombres" => "Mediana", "precio" => 35, "idTipo" => 4, "nombre" => "Hawaiana");
$listaPizzas[] = array("idTamaño" => 3, "nombres" => "Personal", "precio" => 25, "idTipo" => 4, "nombre" => "Hawaiana");
$listaPizzas[] = array("idTamaño" => 4, "nombres" => "Extra Grande", "precio" => 75, "idTipo" => 4, "nombre" => "Hawaiana");


?>