<?php
// para el index
$tipoPelicula = array();
$tipoPelicula[] = array("idTipo" => 1, "nombre" => "Acción");
$tipoPelicula[] = array("idTipo" => 2, "nombre" => "Drama");
$tipoPelicula[] = array("idTipo" => 3, "nombre" => "Terror");
$tipoPelicula[] = array("idTipo" => 4, "nombre" => "Comedia");

// para el resultado
$listaPelicula = array();

$listaPelicula[] = array("idPelicula" => 1, "titulo" => "Rambo Primera Sangre", "precio" => 45, "idTipo" => 1);
$listaPelicula[] = array("idPelicula" => 2, "titulo" => "Avatar", "precio" => 45, "idTipo" => 1);
$listaPelicula[] = array("idPelicula" => 3, "titulo" => "Destino Final", "precio" => 40, "idTipo" => 3);
$listaPelicula[] = array("idPelicula" => 4, "titulo" => "Son como niños", "precio" => 45, "idTipo" => 4);
$listaPelicula[] = array("idPelicula" => 5, "titulo" => "Megalodón", "precio" => 40, "idTipo" => 2);
$listaPelicula[] = array("idPelicula" => 6, "titulo" => "Crespúsculo", "precio" => 45, "idTipo" =>2);

?>