<?php
// para america
$America = array();
$America[] = array("idA" => 1, "nombre" => "Brasil");
$America[] = array("idA" => 2, "nombre" => "Argentina");
$America[] = array("idA" => 3, "nombre" => "Bolivia");


// para europa
$Europa = array();
$Europa[] = array("idE" => 1, "nombre" => "Francia");
$Europa[] = array("idE" => 2, "nombre" => "Alemania");
$Europa[] = array("idE" => 3, "nombre" => "España");


// para africa
$Africa = array();
$Africa[] = array("idAF" => 1, "nombre" => "Senegal");
$Africa[] = array("idAF" => 2, "nombre" => "Marruecos");
$Africa[] = array("idAF" => 3, "nombre" => "Nigeria");



// para asia
$Asia = array();
$Asia[] = array("idAS" => 1, "nombre" => "Japon");
$Asia[] = array("idAS" => 2, "nombre" => "Corea del Sur");
$Asia[] = array("idAS" => 3, "nombre" => "Arabia Saudita");



?>