<?php
// para tipo de pizza
$tipopizza = array();
$tipopizza[] = array("idTipo" => 1, "nombre" => "4 Quesos");
$tipopizza[] = array("idTipo" => 2, "nombre" => "Margarita");
$tipopizza[] = array("idTipo" => 3, "nombre" => "Peperoni");
$tipopizza[] = array("idTipo" => 4, "nombre" => "4 Hawaiana");

// para tipo de tamaño
$tipotamaño = array();
$tipotamaño[] = array("idTamaño" => 1, "nombres" => "Grande");
$tipotamaño[] = array("idTamaño" => 2, "nombres" => "Mediana");
$tipotamaño[] = array("idTamaño" => 3, "nombres" => "Personal");
$tipotamaño[] = array("idTamaño" => 4, "nombres" => "Extra Grande");

// para el resultado
$listaPizzas = array();

$listaPizzas[] = array("idTamaño" => 1, "nombres" => "Grande", "precio" => 55, "idTipo" => 1, "nombre" => "4 Quesos");
$listaPizzas[] = array("idTamaño" => 2, "nombres" => "Mediana", "precio" => 35, "idTipo" => 1, "nombre" => "4 Quesos");
$listaPizzas[] = array("idTamaño" => 3, "nombres" => "Personal", "precio" => 25, "idTipo" => 1, "nombre" => "4 Quesos");
$listaPizzas[] = array("idTamaño" => 4, "nombres" => "Extra Grande", "precio" => 75, "idTipo" => 1, "nombre" => "4 Quesos");
$listaPizzas[] = array("idTamaño" => 1, "nombres" => "Grande", "precio" => 55, "idTipo" => 2, "nombre" => "Margarita");
$listaPizzas[] = array("idTamaño" => 2, "nombres" => "Mediana", "precio" => 35, "idTipo" => 2, "nombre" => "Margarita");
$listaPizzas[] = array("idTamaño" => 3, "nombres" => "Personal", "precio" => 25, "idTipo" => 2, "nombre" => "Margarita");
$listaPizzas[] = array("idTamaño" => 4, "nombres" => "Extra Grande", "precio" => 75, "idTipo" => 2, "nombre" => "Margarita");
$listaPizzas[] = array("idTamaño" => 1, "nombres" => "Grande", "precio" => 55, "idTipo" => 3, "nombre" => "Peperoni");
$listaPizzas[] = array("idTamaño" => 2, "nombres" => "Mediana", "precio" => 35, "idTipo" => 3, "nombre" => "Peperoni");
$listaPizzas[] = array("idTamaño" => 3, "nombres" => "Personal", "precio" => 25, "idTipo" => 3, "nombre" => "Peperoni");
$listaPizzas[] = array("idTamaño" => 4, "nombres" => "Extra Grande", "precio" => 75, "idTipo" => 3, "nombre" => "Peperoni");
$listaPizzas[] = array("idTamaño" => 1, "nombres" => "Grande", "precio" => 55, "idTipo" => 4, "nombre" => "Hawaiana");
$listaPizzas[] = array("idTamaño" => 2, "nombres" => "Mediana", "precio" => 35, "idTipo" => 4, "nombre" => "Hawaiana");
$listaPizzas[] = array("idTamaño" => 3, "nombres" => "Personal", "precio" => 25, "idTipo" => 4, "nombre" => "Hawaiana");
$listaPizzas[] = array("idTamaño" => 4, "nombres" => "Extra Grande", "precio" => 75, "idTipo" => 4, "nombre" => "Hawaiana");


?>